services:
  - type: web
    name: CourtAI
    env: python
    pythonVersion: 3.11.4
    plan: starter   # or whatever plan you use
    buildCommand: |
      pip install --upgrade pip setuptools wheel
      pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PORT
        value: "10000"  # Render usually sets this automatically, just in case
